# Generated by Django 5.2.8 on 2025-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='specialization',
            field=models.CharField(choices=[('WEIGHTLIFTING', 'Weightlifting'), ('CARDIO', 'Cardiovascular Training'), ('YOGA', 'Yoga'), ('PILATES', 'Pilates'), ('HIIT', 'High Intensive Interval Training'), ('FUNCTIONAL', 'Functional Training'), ('GROUP', 'Group Fitness Classes'), ('BODYBUILDING', 'Bodybuilding'), ('POWERLIFTING', 'Powerlifting'), ('FLEXIBILITY', 'Flexibility'), ('ZUMBA', 'Zumba')], max_length=50),
        ),
    ]
