# Generated by Django 5.2.8 on 2025-12-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_alter_instructor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
