# Generated by Django 5.2.8 on 2025-11-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='duration_days',
        ),
    ]
