# Generated by Django 5.2.8 on 2025-12-11 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('members', '0003_remove_member_membership_member_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='subscription',
        ),
        migrations.AddField(
            model_name='member',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('BIANNUAL', 'Bi-Annual'), ('YEARLY', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gym_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructor'),
        ),
    ]
