# Generated by Django 5.2.8 on 2025-12-11 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_alter_instructor_specialization'),
        ('members', '0004_remove_member_subscription_member_has_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gym_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='member',
            name='specialization',
            field=models.CharField(blank=True, choices=[('WEIGHTLIFTING', 'Weightlifting'), ('CARDIO', 'Cardiovascular Training'), ('YOGA', 'Yoga'), ('PILATES', 'Pilates'), ('HIIT', 'High Intensive Interval Training'), ('FUNCTIONAL', 'Functional Training'), ('GROUP', 'Group Fitness Classes'), ('BODYBUILDING', 'Bodybuilding'), ('POWERLIFTING', 'Powerlifting'), ('FLEXIBILITY', 'Flexibility'), ('ZUMBA', 'Zumba')], max_length=50, null=True),
        ),
    ]
