# Generated by Django 5.2.8 on 2025-12-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_gym_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
